config/routes.rb
Rails.application.routes.draw do
  root 'posts#index', as: 'home'

  resources :posts do
   resources :comments
  end

  resources :users ,only: [:new , :create, :show, :edit, :update]

get 'new'=> 'users#new'
get 'show'=> 'users#show'
# patch '/users/:id/edit' => 'users#update'
get '/login' => 'sessions#new'
post 'login' => 'sessions#create'
delete 'logout' => 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  
  def as_json(options = {})
    super(options.merge(include: :user))
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments

  validates :title, presence: true

    def as_json(options = {})
        super(options.merge(include: [:user, comments: {include: :user}]))
    end
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    has_many :posts, dependent: :destroy
    # has_many :comments through :posts

     mount_uploader :avatar, AvatarUploader

    # before_save :update_avatars_attributes

    # private
    #     def update_avatars_attributes
    #         if avatars.present? && avatars_changed?
    #             self.avatars= avatars.file.original_filename
    #             # self.avatars_file_size = avatars_file_size
    #     end
    # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    helper_method :current_user
    
    def current_user 
       @current_user ||= User.find(session[:user_id]) if session[:user_id]  
    end
    def require_user 
      redirect_to '/login' unless current_user
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(comment_params.merge(user_id: current_user.id))
        redirect_to post_path(@post)
    end
    def destroy
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])
        @comment.destroy
        
        redirect_to post_path(@post)
    end
    private def comment_params
        params.require(:comment).permit(:body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  require 'will_paginate/array'
  def index
    @post = Post.paginate(:page => params[:page],:per_page => 2)
  end
  
  def new 
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post =Post.find(params[:id])
  end

  def update 
    @post =Post.find(params[:id])

    if(@post.update(post_params))
        redirect_to @post
      else
        render 'edit'
    end
  end

  def destroy
    @post =Post.find(params[:id])

    @post.destroy
    redirect_to posts_path
  end
  
  def create
    #render plain:params[:post].inspect
    
    @post = Post.create(post_params.merge(user_id: current_user.id))

    if(@post.save)
          redirect_to @post
    else
          render 'new'
    end
  end

  private def post_params
      params.require(:post).permit(:title, :body)
      # authorize @post
  end
  end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
    def create 
        @user = User.find_by_email(params[:session][:email])
        if (@user && @user.authenticate(params[:session][:password]))
            session[:user_id] = @user.id
            redirect_to '/'
        else
            redirect_to 'login'
        end
    end
    def destroy
        session[:user_id] = nil
        redirect_to '/login'
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :check_authorization, only: [:edit, :update]
    def new 
        @user = User.new
    end

    def edit
        @user =User.find(current_user.id)
        current_user
    end
    def update
        # render plain:params[:user].inspect
        @user =User.find(current_user.id)

        if @user.update(params[:user].permit(:name, :surname, :avatar))
            redirect_to @user
        else
            flash[:alert] = "Something went wrong. Please try again"
            render :edit
        end
    end

    def create 
        # render plain:params[:user].inspect
        @user = User.new(user_params) 
        
        if(@user.save)
          session[:user_id] = @user.id 
          redirect_to '/' 
        else
            redirect_to 'new'
        end
    end

    private def user_params 
        params.require(:user).permit(:name, :surname, :email, :password, :avatar)
    end

    private def check_authorization
        unless current_user.id == params[:id].to_i
            redirect_to "/"
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comments.html.erb
<h3> Comments</h3>
<% @post.comments.each do |comment| %>
    <div class="alert alert-secondary">
    <% if comment.user %> 
     <i><a ng-href="#"><%= comment.user.name %></a></i> posted <strong><%= time_ago_in_words(comment.created_at) %> ago </strong>
    <% end %>
    : <%= comment.body %>
    <% if current_user.id == comment.user.id || current_user.id == @post.user_id %>
    <%= link_to ' x ', [comment.post, comment],
                            class: 'close',
                            method: :delete,
                            data: { confirm: 'Are you sure'} %>
    <% end %>                   
    </div>
<% end %>

app/views/comments/_form.html.erb
<div class="form-group">
<h3>Add comment</h3>
<%= form_for([@post, @post.comments.build]) do |f| %>
  <div class="form-group">
    <div class="col-sm-8">
      <%= f.text_area :body, rows: 3, class: "form-control", placeholder: "Please enter a comment", autofocus: true %>
    </div>
  </div>
  <div class="form-group">
    <div class="center col-sm-offset-1 col-sm-10">
      <%= f.submit class: "btn btn-primary btn-lg" %>
    </div>
  </div>
<% end %>
<div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap core CSS -->
    <link href="https://blackrockdigital.github.io/startbootstrap-clean-blog/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="https://blackrockdigital.github.io/startbootstrap-clean-blog/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">

    <!-- Custom styles for this template -->
    <link href="https://blackrockdigital.github.io/startbootstrap-clean-blog/css/clean-blog.min.css" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand" href="#">BLOG</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
        <% if current_user %>
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <%= link_to "Home", home_path %>
            </li>
            <li class="nav-item">
              <%= link_to "Create New", new_post_path %>   
            </li>
            <li class="nav-item">
              <%= link_to current_user.name, show_path%>
            </li>
            <li class="nav-item">
             <%= link_to "Log out", logout_path, method: "delete" %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to "Login",login_path%>  
            </li>
            <li class="nav-item">
              <%= link_to "Sign up" ,new_path%>
            </li>
          </ul>
           <% end %>
        </div>
      </div>
    </nav>
    <header class="masthead" style="background-image: url('https://blackrockdigital.github.io/startbootstrap-clean-blog/img/home-bg.jpg')">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="site-heading">
              <h1>BlogTimeline</h1>
              <span class="subheading">Shared stories</span>
            </div>
          </div>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer>
    <script src="https://blackrockdigital.github.io/startbootstrap-clean-blog/vendor/jquery/jquery.min.js"></script>
    <script src="https://blackrockdigital.github.io/startbootstrap-clean-blog/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="https://blackrockdigital.github.io/startbootstrap-clean-blog/js/clean-blog.min.js"></script>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <ul class="list-inline text-center">
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fas fa-circle fa-stack-2x"></i>
                    <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fas fa-circle fa-stack-2x"></i>
                    <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fas fa-circle fa-stack-2x"></i>
                    <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
            </ul>
            <p class="copyright text-muted">Copyright © Your Website 2018</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="container">
<h1>Edit Post</h1>

<%= form_for :post, url:post_path(@post), method: :patch do |f| %>
    <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg %></div>
    <% end %>
    <% end %>
<p>
    <%= f.label :title %>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
</p>
<p>
    <%= f.label :body %>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
</p>
<p>
    <%= f.submit({:class => 'btn btn-primary btn-lg'}) %>
</p>
<% end %>
</div>

app/views/posts/index.html.erb
<div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="post-preview">
             <% @post.each do |post| %>
             <a href="/posts/1">
              <h2 class="post-title">
               <%= post.title %>
              </h2>
              <h3 class="post-subtitle">
                <%= post.body %>
              </h3>
            </a>
            <p class="post-meta">
            <% if post.user %> 
                posted by <a ng-href="#"><%= post.user.name %></a>
            <% end %>
            <%= time_ago_in_words(post.created_at) %> ago
            </p>
          </div>
           <% end %>
          <hr>
          <%# <%= link_to "Read More", post_path(post), :class => 'btn btn-secondary'%>
          <hr>
          <!-- Pager -->
          <div class="clearfix">
            <%= will_paginate @post  %>
          </div>
        </div>
      </div>
    </div>

app/views/posts/new.html.erb
<div class="container">
<%= form_for :post, url:posts_path do |f| %>
<h1>Add Post</h1>
    <div class="control-group">
    <div class="form-group floating-label-form-group controls">
        <%= f.label :title %>
        <%= f.text_field(:title, {:class => 'form-control',:placeholder =>"Post Title"}) %>
        <p class="help-block text-danger"></p>
    </div>
    </div>
    <div class="control-group">
    <div class="form-group floating-label-form-group controls">
        <%= f.label :body %>
        <%= f.text_area(:body, {:class => 'form-control',:placeholder =>"Post Body"}) %>
        <p class="help-block text-danger"></p>
    </div>
    </div>
    <br>
    <div id="success"></div>
    <div class="form-group">
    <%= f.submit({:class => 'btn btn-primary btn-lg'}) %>
    </div>
<% end %>
</div>

app/views/posts/show.html.erb
<div class="container">
<h2><%= @post.title %></h2>
<p><%= @post.body %></p>
<% if current_user.id == @post.user_id %> 
<hr>
<%= link_to "Edit",edit_post_path(@post),:class => 'btn btn-secondary' %>
<%= link_to "Delete",post_path(@post),
                            method: :Delete,
                            data: {confirm: 'Are you sure?'},
                            :class => 'btn btn-danger'%>
<hr>
<% end %>
<%= render 'comments/comments'%>
<%= render 'comments/form' %> 
</div>

app/views/users/edit.html.erb
<div class="container">
 <%= form_for(@user, html: {multipart: true })  do |f|  %>
<div class="form-group has-success has-feedback">
    <h1>Edit Profile</h1>
</div>

 <div class="form-group has-success has-feedback">
    <%= f.label :name, class: "sr-only" %>
    <%= f.text_field(:name, class: "form-control", placeholder: "First Name") %>
      <span class="glyphicon glyphicon-ok form-control-feedback" aria-hidden="true"></span>
</div>

<div class="form-group has-success has-feedback">
    <%= f.label :surname, class: "sr-only" %>                  
    <%= f.text_field(:surname, class: "form-control", placeholder: "Last Name") %>
      <span class="glyphicon glyphicon-ok form-control-feedback" aria-hidden="true"></span>
</div>
<div class="padding">
<div class="form-group has-success has-feedback">
    <%= f.file_field :avatar %>
</div> 
</div>
<div class="modal-footer">
  <%= f.submit 'Save Changes', class: 'btn btn-primary' %>
   <%= link_to 'Close', "/users/id", class: "btn btn-default", data: {dismiss: "modal"} %>
    </div>
  <% end %> 
</div>

app/views/users/new.html.erb
<div class="container">
 <%= form_for :user,, html: {multipart: true }),url:users_path  do |f| %>

<div class="form-group has-success has-feedback">
    <h1>Sign Up</h1>
</div>

 <div class="form-group has-success has-feedback">
    <%= f.label :name, class: "sr-only" %>
    <%= f.text_field(:name, class: "form-control", placeholder: "First Name") %>
      <span class="glyphicon glyphicon-ok form-control-feedback" aria-hidden="true"></span>
</div>

<div class="form-group has-success has-feedback">
    <%= f.label :surname, class: "sr-only" %>                  
    <%= f.text_field(:surname, class: "form-control", placeholder: "Last Name") %>
      <span class="glyphicon glyphicon-ok form-control-feedback" aria-hidden="true"></span>
</div>

  <div class="form-group has-success has-feedback">
    <%= f.label :email, class: "sr-only" %>
    <%= f.text_field(:email, class: "form-control", placeholder: "Email") %>
      <span class="glyphicon glyphicon-ok form-control-feedback" aria-hidden="true"></span>
</div>

  <div class="form-group has-success has-feedback">
    <%= f.label :password, class: "sr-only" %>
    <%= f.password_field(:password, type: "password", class: "form-control", placeholder: "Password") %>
      <span class="glyphicon glyphicon-ok form-control-feedback" aria-hidden="true"></span>
  </div>

  <div class="form-group has-success has-feedback">
    <%= f.label :password, class: "sr-only" %>
    <%= f.password_field(:password, type: "password", class: "form-control", placeholder: "Confirm Password") %>
      <span class="glyphicon glyphicon-ok form-control-feedback" aria-hidden="true"></span>
</div>  
<div class="padding">
<div class="form-group has-success has-feedback">
    <%= f.file_field :avatar %>
</div> 
</div>
<div class="modal-footer">
  <%= link_to 'Close', "/", class: "btn btn-default", data: {dismiss: "modal"} %>
  <%= f.submit 'Register', class: 'btn btn-primary' %>
    </div>
  <% end %> 
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="col s12 m7">
    <h2 class="header">User Profile</h2>
    <div class="card horizontal">
    <div class="card-image"> 
       <%= image_tag current_user.avatar.url(:thumb) if current_user.avatar? %>
      </div>
      <div class="card-stacked">
        <div class="card-content">
        <h5><%= current_user.name %><%= current_user.surname %></h5>
          <p>Email :<%= current_user.email %></p>
        </div>
        <div class="card-action">
         <%= link_to "Edit", edit_user_path(current_user),:class => 'btn btn-secondary'%>
        </div>
        <div class="clearfix">
        <a class="btn btn-primary float-left" href="/">Go Home →</a>
        </div>
      </div>
    </div>
  </div>
</div>